apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
    replicas: 5
    selector:
        name: myapp
    template:
        metadata:
          name: myapp-nginx
          labels:
                name: myapp
        spec:
          containers:
            - name: myapp-nginx
              image: nginx
              ports:
                    - containerPort: 80
