---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-nginx
  labels:
        name: myapp
        version: v2
spec:
  containers:
    - name: myapp
      image: nginx
      ports:
      - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: myapp-httpd
  labels:
        name: myapp
        version: v1
spec:
  containers:
    - name: myapp
      image: httpd
      ports:
      - containerPort: 80

